CODE SEGMENT
ASSUME CS: CODE, DS: DATA, ES: EXTRA

DATA SEGMENT
    OPR1 DW 5169H        
    OPR2 DW 1000H        
DATA ENDS

EXTRA SEGMENT
    DIFF DW ?            
EXTRA ENDS

START:
    MOV AX, DATA         ; REGISTER ADDRESING MODE
    MOV DS, AX           
    MOV AX, EXTRA
    MOV ES, AX           ; REGISTER ADDRESING MODE
    MOV BX, OFFSET OPR1  ; DIRECT ADDRESING MODE
    MOV AX, [BX]         ; BASE ADDRESING MODE
    SUB AX, OPR2         ; DIRECT ADDRESING MODE
    MOV DIFF, AX         ; DIRECT ADDRESING MODE
    INT 03H              

CODE ENDS
END START
