ASSUME CS: CODE, DS: DATA
DATA SEGMENT
    STRING DB 'MICROPROCESSOR$'
    COUNT EQU ($-STRING)
    ORG 0070H
DATA ENDS

EXTRA SEGMENT
    ORG 0010H
    STRING1 DB ?
EXTRA ENDS

CODE SEGMENT
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, EXTRA
    MOV ES, AX
    MOV SI, OFFSET STRING
    MOV DI, OFFSET STRING1
    MOV CL, COUNT
    CLD
REP MOVSB
    INT 03H
CODE ENDS
END START