ASSUME CS: CODE, DS: DATA, ES: EXTRA
DATA SEGMENT
    STRING1 DB 'MICROPROCESSOR AND INTERFACING LAB$'
    ORG 0070H
DATA ENDS

EXTRA SEGMENT
    ORG 0010H
    STRING2 DB 40 DUP(0)
EXTRA ENDS

CODE SEGMENT
START:
    MOV AX, DATA
    MOV DS, AX
    MOV AX, EXTRA
    MOV ES, AX
    MOV SI, OFFSET STRING1
    MOV DI, OFFSET STRING2
    CLD
    MOV CX, 15
    REP MOVSB
    CLD
    MOV SI, OFFSET STRING1
    ADD SI, 19
    MOV CX, 15
    REP MOVSB
    INT 03H
CODE ENDS
END START