ASSUME CS:CODE, DS:DATA
DATA SEGMENT
    STRING DB 'HELLO, WORLD$', 0DH, 0AH, '$'
DATA ENDS

CODE SEGMENT
START:
    MOV AX, DATA
    MOV DS, AX
    MOV DX, OFFSET STRING
    MOV AH, 09H
    INT 21H
    MOV AH, 4CH
    INT 21H

CODE ENDS
END START